"C:/Program Files/PostgreSQL/9.4/bin\pg_dump.exe" --host localhost --port 5432 --username "postgres" --no-password  --format directory --create --clean --encoding UTF8 --inserts --column-inserts --verbose --file "C:\Users\albert.wang\OneDrive\workspace\go\src\github.com\saiyawang\etl\resource\customer.backup" --table "public.customer" "etl"
"C:/Program Files/PostgreSQL/9.4/bin\pg_dump.exe" --host localhost --port 5432 --username "postgres" --no-password  --format directory --create --clean --encoding UTF8 --inserts --column-inserts --verbose --file "C:\Users\albert.wang\OneDrive\workspace\go\src\github.com\saiyawang\etl\resource\device.backup" --table "public.device" "etl"
"C:/Program Files/PostgreSQL/9.4/bin\pg_dump.exe" --host localhost --port 5432 --username "postgres" --no-password  --format directory --create --clean --encoding UTF8 --inserts --column-inserts --verbose --file "C:\Users\albert.wang\OneDrive\workspace\go\src\github.com\saiyawang\etl\resource\deviceindmp.backup" --table "public.deviceindmp" "etl"
"C:/Program Files/PostgreSQL/9.4/bin\pg_dump.exe" --host localhost --port 5432 --username "postgres" --no-password  --format directory --create --clean --encoding UTF8 --inserts --column-inserts --verbose --file "C:\Users\albert.wang\OneDrive\workspace\go\src\github.com\saiyawang\etl\resource\deviceinus.backup" --table "public.deviceinus" "etl"
"C:/Program Files/PostgreSQL/9.4/bin\pg_dump.exe" --host localhost --port 5432 --username "postgres" --no-password  --format directory --create --clean --encoding UTF8 --inserts --column-inserts --verbose --file "C:\Users\albert.wang\OneDrive\workspace\go\src\github.com\saiyawang\etl\resource\deviceinworld.backup" --table "public.deviceinworld" "etl"
"C:/Program Files/PostgreSQL/9.4/bin\pg_dump.exe" --host localhost --port 5432 --username "postgres" --no-password  --format directory --create --clean --encoding UTF8 --inserts --column-inserts --verbose --file "C:\Users\albert.wang\OneDrive\workspace\go\src\github.com\saiyawang\etl\resource\devicetype.backup" --table "public.devicetype" "etl"
"C:/Program Files/PostgreSQL/9.4/bin\pg_dump.exe" --host localhost --port 5432 --username "postgres" --no-password  --format directory --create --clean --encoding UTF8 --inserts --column-inserts --verbose --file "C:\Users\albert.wang\OneDrive\workspace\go\src\github.com\saiyawang\etl\resource\location.backup" --table "public.location" "etl"
"C:/Program Files/PostgreSQL/9.4/bin\pg_dump.exe" --host localhost --port 5432 --username "postgres" --no-password  --format directory --create --clean --encoding UTF8 --inserts --column-inserts --verbose --file "C:\Users\albert.wang\OneDrive\workspace\go\src\github.com\saiyawang\etl\resource\locationrole.backup" --table "public.locationrole" "etl"
"C:/Program Files/PostgreSQL/9.4/bin\pg_dump.exe" --host localhost --port 5432 --username "postgres" --no-password  --format directory --create --clean --encoding UTF8 --inserts --column-inserts --verbose --file "C:\Users\albert.wang\OneDrive\workspace\go\src\github.com\saiyawang\etl\resource\sku.backup" --table "public.sku" "etl"

C